-- =========================================================================
--                          City Cleaning Logic
-- =========================================================================

SELECT 
    recipient_city,
    recipient_state,
    recipient_zip,
CASE    
            WHEN recipient_city = '0cala' THEN 'Ocala'
            WHEN recipient_city = 'C0ral Gables' THEN 'Coral Gables'
            
            -- MILITARY FIXES
            WHEN recipient_city = 'Fpo Ap' THEN 'Fpo'
            
            -- STATE-SPECIFIC TYPOS (AR/AS/AZ)
            WHEN recipient_city IN ('Ft. Smith', ' Ft. Smith') AND recipient_state = 'AR' THEN 'Fort Smith'
            WHEN recipient_city = 'Mc Gehee' AND recipient_state = 'AR' THEN 'McGehee'
            WHEN recipient_city = 'Rodgers' AND recipient_state = 'AR' THEN 'Rogers'
            WHEN recipient_city IN ('Hot Springs National', 'Hot Springs National Park') AND recipient_state = 'AR' THEN 'Hot Springs'
            
            WHEN recipient_city = 'Pagopago' AND recipient_state = 'AS' THEN 'Pago Pago'
            WHEN recipient_city = 'Blvd Phoenix' AND recipient_state = 'AZ' THEN 'Phoenix'
            
            -- AZ Standardizations
            WHEN recipient_city = 'Paradise' AND recipient_zip = '85253' THEN 'Paradise Valley'
            WHEN recipient_city = 'Mohave' AND recipient_zip = '86442' THEN 'Bullhead City'
            WHEN recipient_city = 'Mohave' AND recipient_zip = '86440' THEN 'Mohave Valley'
            WHEN recipient_city = 'Pinetop' AND recipient_zip = '85935' THEN 'Pinetop-Lakeside'
            
            -- CA Standardizations
            WHEN recipient_city = 'Dentistry Of San Francisco' THEN 'San Francisco'
            WHEN recipient_city = 'Duarte,' THEN 'Duarte'
            WHEN recipient_city = 'East Rancho Domingue' THEN 'East Rancho Dominguez'
            
            -- Specific Typos (AK/AL)
            WHEN recipient_city = 'Anchoage' THEN 'Anchorage'
            WHEN recipient_city = 'Juneu' THEN 'Juneau'
            WHEN recipient_city = 'Alex City' THEN 'Alexander City'
            WHEN recipient_city = 'Gadseden' THEN 'Gadsden'
            WHEN recipient_city = 'Mountain Brk' THEN 'Mountain Brook'
            WHEN recipient_city = 'Bayou Labatre' THEN 'Bayou La Batre'

            WHEN recipient_city = 'Flinkt' THEN 'Flint'
            WHEN recipient_city = 'Fleming Isle' THEN 'Fleming Island'
            WHEN recipient_city = 'Flemingten' THEN 'Flemington'
            WHEN recipient_city = 'Arlingtonheights' THEN 'Arlington Heights'
            WHEN recipient_city = 'Flushinh' THEN 'Flushing'
            WHEN recipient_city = ', Albuquerque' THEN 'Albuquerque'
            WHEN recipient_city = ', Greensboro' THEN 'Greensboro' 				
            WHEN recipient_city = 'Owens X Rds' THEN 'Owens Cross Roads' 			
            WHEN recipient_city = '00612' AND recipient_zip = '00612' THEN 'Arecibo'
            WHEN recipient_city = 'Az 85281' AND recipient_zip = '85281' THEN 'Tempe'
            WHEN recipient_city = '1116030865' AND recipient_zip = '23116' THEN 'Mechanicsville'
            WHEN recipient_city IN ('02111', '021111552') AND recipient_zip = '02111' THEN 'Boston'
            WHEN recipient_city = '1120 15th St' AND recipient_zip = '30912' THEN 'Augusta'
            WHEN recipient_city = '1125 W Jefferson Street' AND recipient_zip = '46131' THEN 'Franklin'
            WHEN recipient_city = '11475 Olde Cabin Rd Ste 200' AND recipient_zip = '63141' THEN 'Saint Louis'
            WHEN recipient_city = '1258 Brownswitch Rd, Suite A' AND recipient_zip = '70817' THEN 'Baton Rouge'
            WHEN recipient_city = '12827 Harbor Blvd Ste G1 Garden' AND recipient_zip = '92840' THEN 'Garden Grove'
            WHEN recipient_city = '145 Falmouth Rd' AND recipient_zip = '02601' THEN 'Hyannis'
            WHEN recipient_city = '150 N Park Trail' AND recipient_zip = '30281' THEN 'Stockbridge'
            WHEN recipient_city = '173 Terrace St' AND recipient_zip = '07641' THEN 'Haworth'
            WHEN recipient_city = '19131' AND recipient_zip = '19131' THEN 'Philadelphia'
            WHEN recipient_city = '11978' THEN 'Westhampton Beach'
            WHEN recipient_city = 'Stamford Ct 06904' THEN 'Stamford'
            WHEN recipient_city = '850 Columbia Rd. Westlake, 44145' THEN 'Westlake'
            WHEN recipient_city = 'P O Box 600' AND teaching_hospital_name LIKE '%Mayaguez%' THEN 'Mayaguez'
            WHEN recipient_city = 'Tam101' AND recipient_zip = '33609' THEN 'Tampa'
            WHEN recipient_city = '250' AND recipient_zip = '85224' THEN 'Chandler'
            WHEN recipient_city = 'Ste 628' AND recipient_zip = '35209' THEN 'Birmingham'
            WHEN recipient_city IN ('South Portland, Me 04106', 'South Portland Me 04106') THEN 'South Portland'
            WHEN recipient_city = 'Ste 1 Fort Myers' THEN 'Fort Myers'
            WHEN recipient_city = 'Ste 101 Rockledge' THEN 'Rockledge'
            WHEN recipient_city = 'Ste 220 Apopka' THEN 'Apopka'
            WHEN recipient_city = 'Ste 1a Sarasota' THEN 'Sarasota'
            WHEN recipient_city = '3230 Church St Valatie' THEN 'Valatie'
            WHEN recipient_city = 'Box 4 New York,' THEN 'New York'
            WHEN recipient_city LIKE 'Kansas City, Mo%' THEN 'Kansas City'
            WHEN recipient_city LIKE 'Houston, Tx%' THEN 'Houston'
            WHEN recipient_city LIKE 'Smyrna, Ga%' THEN 'Smyrna'
            WHEN recipient_city LIKE 'Rochester, Mn%' THEN 'Rochester'
            WHEN recipient_city LIKE 'Boston,%' THEN 'Boston'
            WHEN recipient_city LIKE 'Durham, Nc%' THEN 'Durham'
            WHEN recipient_city LIKE 'Knoxville Tn %' THEN 'Knoxville'
            WHEN recipient_city LIKE 'Las Vegas  Nv%' THEN 'Las Vegas'
            WHEN recipient_city LIKE 'Mason, Oh %' THEN 'Mason'
            WHEN recipient_city LIKE 'Midlothian Va %' THEN 'Midlothian'
            WHEN recipient_city LIKE 'Naperville, Il %' THEN 'Naperville'
            WHEN recipient_city LIKE 'New York, Ny %' OR recipient_city = 'New York' THEN 'New York'
            WHEN recipient_city LIKE 'Salinas Ca %' THEN 'Salinas'
            WHEN recipient_city LIKE 'South Portland, Me%' THEN 'South Portland'
            WHEN recipient_city LIKE 'Stamford  Ct%' THEN 'Stamford'
            WHEN recipient_city LIKE 'Dallas%' THEN 'Dallas'
            WHEN recipient_zip = '35210' THEN 'Birmingham'
            WHEN recipient_zip = '49016' THEN 'Battle Creek'
            WHEN recipient_zip = '93483' THEN 'Templeton'
            WHEN recipient_zip = '28612' THEN 'Collettsville'
            WHEN recipient_zip = '44145' THEN 'Westlake'
            WHEN recipient_zip = '33161' THEN 'Miami'
            WHEN recipient_zip = '60453' THEN 'Oak Lawn'
            WHEN recipient_zip = '89148' THEN 'Las Vegas'
            WHEN recipient_zip = '32164' THEN 'Smyrna Beach'
            WHEN recipient_zip = '07753' THEN 'Neptune'
            WHEN recipient_zip = '63110' THEN 'Saint Louis'
            WHEN recipient_zip = '32137' THEN 'Palm Coast'
            WHEN recipient_zip = '00976' THEN 'San Juan'
            WHEN recipient_zip = '19044' THEN 'Horsham'
            WHEN recipient_zip = '91007' THEN 'Arcadia'
            WHEN recipient_zip = '77036' THEN 'Houston'
            WHEN recipient_zip = '73110' THEN 'Oklahoma City'
            WHEN recipient_zip = '78041' THEN 'Laredo'
            WHEN recipient_zip = '78229' THEN 'San Antonio'
            WHEN recipient_zip = '92037' THEN 'La Jolla'
            WHEN recipient_zip = '93901' THEN 'Salinas'
            WHEN recipient_zip = '92278' THEN 'Twentynine Palms'
            WHEN recipient_zip = '94546' THEN 'Castro Valley'
            WHEN recipient_zip IN ('80045', '80230') THEN 'Denver'
            WHEN recipient_zip = '33432' THEN 'Boca Raton'
            WHEN recipient_zip = '32703' THEN 'Apopka'
            WHEN recipient_zip = '33912' THEN 'Fort Myers'
            WHEN recipient_zip = '32955' THEN 'Sebastian'
            WHEN recipient_zip = '34239' THEN 'Sarasota'
            WHEN recipient_zip = '33704' THEN 'Saint Petersburg'
            WHEN recipient_zip = '34145' THEN 'Bonita Springs'
            WHEN recipient_zip IN ('30342', '30312') THEN 'Atlanta'
            WHEN recipient_zip = '30080' THEN 'Smyrna'
            WHEN recipient_zip = '30143' THEN 'Jasper'
            WHEN recipient_zip = '30542' THEN 'Flowery Branch'
            WHEN recipient_zip = '92350' THEN 'Lytle Creek'
            WHEN recipient_zip = '52242' THEN 'Coralville'
            WHEN recipient_zip = '60016' THEN 'Des Plaines'
            WHEN recipient_zip = '40536' THEN 'Lexington'
            WHEN recipient_zip = '40018' THEN 'Eminence'
            WHEN recipient_zip IN ('40201', '40215') THEN 'Louisville'
            WHEN recipient_zip = '42647' THEN 'Stearns'
            WHEN recipient_zip = '20735' THEN 'Clinton'
            WHEN recipient_zip = '04106' THEN 'South Portland'
            WHEN recipient_zip = '48098' THEN 'Troy'
            WHEN recipient_zip IN ('48310', '48313') THEN 'Sterling Heights'
            WHEN recipient_zip = '55976' THEN 'Stewartville'
            WHEN recipient_zip = '55905' THEN 'Rochester'
            WHEN recipient_zip = '63670' THEN 'Sainte Genevieve'
            WHEN recipient_zip = '27410' THEN 'Greensboro'
            WHEN recipient_zip = '27534' THEN 'Goldsboro'
            WHEN recipient_zip = '58482' THEN 'Steele'
            WHEN recipient_zip = '03878' THEN 'Rochester'
            WHEN recipient_zip = '08886' THEN 'Stewartsville'
            WHEN recipient_zip = '89145' THEN 'Las Vegas'
            WHEN recipient_zip = '17578' THEN 'Stevens'
            WHEN recipient_zip = '02906' THEN 'Providence'
            WHEN recipient_zip = '57105' THEN 'Sioux Falls'
            WHEN recipient_zip = '37922' THEN 'Knoxville'
            WHEN recipient_zip = '77070' THEN 'Houston'
            WHEN recipient_zip = '84113' THEN 'Salt Lake City'
            WHEN recipient_zip = '22031' THEN 'Fairfax'
            WHEN recipient_zip = '22191' THEN 'Woodbridge'
            WHEN recipient_zip IN ('20166', '20164') THEN 'Sterling'
            WHEN recipient_zip = '22304' THEN 'Alexandria'
            WHEN recipient_zip = '25701' THEN 'Huntington'
            WHEN recipient_zip = '26506' THEN 'Morgantown'
            WHEN recipient_zip = '90011' AND recipient_city = 'New York' THEN 'Los Angeles'
            WHEN recipient_state = 'AL' AND recipient_city IN ('Birimingham','Birmimgham','Birmingahm','S Birmingham') THEN 'Birmingham'
            WHEN recipient_state = 'AL' AND recipient_city IN ('Fair Hope','Fairhop','Rairhope') THEN 'Fairhope'
            WHEN recipient_state = 'AL' AND recipient_city = 'Ft Payne' THEN 'Fort Payne'
            WHEN recipient_state = 'AL' AND recipient_city IN ('Huntsviile','Hutnsville') THEN 'Huntsville'
            WHEN recipient_state = 'AL' AND recipient_city IN ('Mt Vernon','Mt. Vernon') THEN 'Mount Vernon'
            WHEN recipient_state = 'AL' AND recipient_city = 'Northalabaster' THEN 'North Alabaster'
            WHEN recipient_state = 'AL' AND recipient_city = 'Russelville' THEN 'Russellville'
            WHEN recipient_state = 'AL' AND recipient_city = 'Tisca;ppsa' THEN 'Tuscaloosa'
            WHEN recipient_state = 'AL' AND recipient_city IN ('Mc Intosh','Mcintosh') THEN 'McIntosh'
            WHEN recipient_state = 'AL' AND recipient_city = 'Groveoak' THEN 'Grove Oak'
            WHEN recipient_state = 'AR' AND recipient_city = 'Batesvile' THEN 'Batesville'
            WHEN recipient_state = 'AR' AND recipient_city = 'Blythevile' THEN 'Blytheville'
            WHEN recipient_state = 'AR' AND recipient_city = 'Faetteville' THEN 'Fayetteville'
            WHEN recipient_state = 'AR' AND recipient_city IN ('Fort Smtih','Fortsmith') THEN 'Fort Smith'
            WHEN recipient_state = 'AR' AND recipient_city = 'Mtn Home' THEN 'Mountain Home'
            WHEN recipient_state = 'AR' AND recipient_city IN ('Searchy','Sesrcy') THEN 'Searcy'
            WHEN recipient_state = 'AR' AND recipient_city = 'Cherokee Vlg' THEN 'Cherokee Village'
            WHEN recipient_state = 'AR' AND recipient_city = 'Hamptom' THEN 'Hampton'
            WHEN recipient_state = 'AR' AND recipient_city = 'Little Rock,' THEN 'Little Rock'
            WHEN recipient_state = 'AZ' AND recipient_city = 'Apache Jct' THEN 'Apache Junction'
            WHEN recipient_state = 'AZ' AND recipient_city IN ('Gilber','Golbert') THEN 'Gilbert'
            WHEN recipient_state = 'AZ' AND recipient_city IN ('Pheonix','Phoeniz','Phoennix','Phoenxi','Ophoenix') THEN 'Phoenix'
            WHEN recipient_state = 'AZ' AND recipient_city = 'Prescottvalley' THEN 'Prescott Valley'
            WHEN recipient_state = 'AZ' AND recipient_city IN ('Tucson, Az','Tucon','Tucsan','Tucso','Tuson') THEN 'Tucson'
            WHEN recipient_state = 'AZ' AND recipient_city = 'Oro Valley,' THEN 'Oro Valley'
            WHEN recipient_state = 'AZ' AND recipient_city = 'Lk Montezuma' THEN 'Lake Montezuma'
            WHEN recipient_state = 'AZ' AND recipient_city IN ('Lk Havasu Cty','Lake Havasu') THEN 'Lake Havasu City'
            WHEN recipient_state = 'AZ' AND recipient_city = 'Gila' THEN 'Gila Bend'
            WHEN recipient_state = 'AZ' AND recipient_city = 'Glendal' THEN 'Glendale'
            WHEN recipient_state = 'CA' AND recipient_city IN ('Bakerfield','Bakersfiled') THEN 'Bakersfield'
            WHEN recipient_state = 'CA' AND recipient_city = 'Belvedere Tiburon' THEN 'Tiburon'
            WHEN recipient_state = 'CA' AND recipient_city = 'Berkley' THEN 'Berkeley'
            WHEN recipient_state = 'CA' AND recipient_city = 'Diamond Spgs' THEN 'Diamond Springs'
            WHEN recipient_state = 'CA' AND recipient_city IN ('Hunington Beach','Hunting Beach','Huntingtn Bch') THEN 'Huntington Beach'
            WHEN recipient_state = 'CA' AND recipient_city IN ('La Jolia','La Joll A') THEN 'La Jolla'
            WHEN recipient_state = 'CA' AND recipient_city IN ('Las Angeles','Los Angales','Los Angelas','Los Angels','Losangeles') THEN 'Los Angeles'
            WHEN recipient_state = 'CA' AND recipient_city = 'Marina Del Ray' THEN 'Marina del Rey'
            WHEN recipient_state = 'CA' AND recipient_city IN ('Mission Veijo','Mission Viejo') THEN 'Mission Viejo'
            WHEN recipient_state = 'CA' AND recipient_city IN ('New Port Beach','Nweport Beach') THEN 'Newport Beach'
            WHEN recipient_state = 'CA' AND recipient_city = 'Pacific Palasades' THEN 'Pacific Palisades'
            WHEN recipient_state = 'CA' AND recipient_city = 'Palo Verdes Estates' THEN 'Palos Verdes Estates'
            WHEN recipient_state = 'CA' AND recipient_city IN ('Rancho Cucamon','Rancho Cucuamonga') THEN 'Rancho Cucamonga'
            WHEN recipient_state = 'CA' AND recipient_city IN ('S Lake Tahoe','South Lake Tahoe') THEN 'South Lake Tahoe'
            WHEN recipient_state = 'CA' AND recipient_city IN ('S San Fran','S. San Francisco','San Francisisco','San Franscisco','San Fransicso','So San Francisco','Sf') THEN 'San Francisco'
            WHEN recipient_state = 'CA' AND recipient_city IN ('San Juan Capo','San Juan Capristrano') THEN 'San Juan Capistrano'
            WHEN recipient_state = 'CA' AND recipient_city = 'Thousands Oaks' THEN 'Thousand Oaks'
            WHEN recipient_state = 'CA' AND recipient_city IN ('W Covina','West Coovia','West Corvina') THEN 'West Covina'
            WHEN recipient_state = 'TX' AND recipient_city IN ('Flower Mount', 'Flowermound') THEN 'Flower Mound'
            WHEN recipient_state = 'WV' AND recipient_city = 'So Charleston' THEN 'South Charleston'
            WHEN recipient_state = 'WV' AND recipient_city = 'Scott Depot25560' THEN 'Scott Depot'
            WHEN recipient_state = 'WV' AND recipient_city = 'Pakersburg' THEN 'Parkersburg'
            WHEN recipient_state = 'WV' AND recipient_city = 'Pt Pleasant' THEN 'Point Pleasant'
            WHEN recipient_state = 'WV' AND recipient_city IN ('Bridgepoet','Bridgport') THEN 'Bridgeport'
            WHEN recipient_state = 'WV' AND recipient_city = 'Berkeley Spgs' THEN 'Berkeley Springs'
            WHEN recipient_state = 'WI' AND recipient_city = 'White Fish Bay' THEN 'Whitefish Bay'
            WHEN recipient_state = 'WI' AND recipient_city = 'Menomonee Fls' THEN 'Menomonee Falls'
            WHEN recipient_state = 'WI' AND recipient_city IN ('Milwauikee','Milwaukee','Milwaukeew','Milwuakee') THEN 'Milwaukee'
            WHEN recipient_city LIKE '% Hts' THEN REPLACE(recipient_city, ' Hts', ' Heights')
            WHEN recipient_city LIKE '% Hts.%' THEN REPLACE(recipient_city, ' Hts.', ' Heights')
            WHEN recipient_city LIKE '% Hgts' THEN REPLACE(recipient_city, ' Hgts', ' Heights')
            WHEN recipient_city LIKE '% Hls' THEN REPLACE(recipient_city, ' Hls', ' Hills')
            WHEN recipient_city LIKE '% Spgs' THEN REPLACE(recipient_city, ' Spgs', ' Springs')
            WHEN recipient_city LIKE '% Sprgs' THEN REPLACE(recipient_city, ' Sprgs', ' Springs')
            WHEN recipient_city LIKE '% Twp' THEN REPLACE(recipient_city, ' Twp', ' Township')
            WHEN recipient_city LIKE '% Ft' THEN REPLACE(recipient_city, ' Ft', ' Fort')
            WHEN recipient_city LIKE '% St' THEN REPLACE(recipient_city, ' St', ' Saint')
            WHEN recipient_city LIKE '% St.' THEN REPLACE(recipient_city, ' St.', ' Saint')
            WHEN recipient_city LIKE '% Mt' THEN REPLACE(recipient_city, ' Mt', ' Mount')
            WHEN recipient_city LIKE '% Ste' THEN REPLACE(recipient_city, ' Ste', ' Sainte')    
        ELSE null
    END as clean_city_test

FROM general_payments
WHERE recipient_city REGEXP '^[0-9]' 
   OR recipient_city LIKE ',%'
   OR recipient_city IN ('0CALA', 'Pheonix', 'C0ral Gables', 'Flinkt', 'Fleming Isle')
   OR recipient_city LIKE '% Hts'
   OR (recipient_zip = '23116') 
LIMIT 50;
