-- =========================================================================
-- Migration Workflow (ELT - Load Raw Data)
-- =========================================================================

DELIMITER $$

CREATE PROCEDURE MigrateStaging()
BEGIN
    DECLARE batch_size INT DEFAULT 10000;
    DECLARE min_id BIGINT;
    DECLARE max_id BIGINT;
    DECLARE current_id BIGINT;
    DECLARE last_processed_id BIGINT;
    DECLARE total_rows_migrated INT DEFAULT 0;
    DECLARE rows_in_this_batch INT DEFAULT 0;
    
    -- 1. Get the range of the staging table
    SELECT MIN(staging_id), MAX(staging_id) INTO min_id, max_id FROM stg_general_payments;
    
    -- 2. Find where this specific process last left off
    SELECT MAX(batch_end_id) INTO last_processed_id 
    FROM migration_log 
    WHERE process_name = 'MigrateStaging' AND log_type = 'BATCH';
    
    IF last_processed_id IS NULL THEN
        SET current_id = min_id;
    ELSE
        SET current_id = last_processed_id + 1;
    END IF;
    
    SELECT CONCAT('Starting Migration from ID: ', current_id) AS Status;

    -- START OF LOOP
    WHILE current_id <= max_id DO
        
        START TRANSACTION;        
       
        INSERT IGNORE INTO general_payments (
            payment_id,
            record_id, change_type, program_year, payment_date, publication_date,
            amount_usd, number_of_payments, payment_nature, payment_form,
            recipient_profile_id, recipient_npi, recipient_type, 
            
            
            recipient_first_name, recipient_middle_name, recipient_last_name, recipient_name_suffix,
            teaching_hospital_name,
            
            -- Full Name is LEFT NULL (To be generated by Cleaning Scripts)
            recipient_full_name, 
            
            recipient_specialty, recipient_license_state, teaching_hospital_ccn,
            recipient_address_line1, recipient_address_line2,
            recipient_city, recipient_state, recipient_zip, recipient_country, recipient_province,
            payer_name, payer_id,
            subsidiary_name, subsidiary_id, subsidiary_state, subsidiary_country,
            name_of_third_party_entity,
            physician_ownership_indicator, third_party_payment_recipient_indicator,
            charity_indicator, related_product_indicator, dispute_status, contextual_information,
            travel_city, travel_state, travel_country,
            product_type_1, product_name_1, product_category_1, product_ndc_1,
            product_type_2, product_name_2, product_category_2, product_ndc_2,
            product_type_3, product_name_3, product_category_3, product_ndc_3,
            product_type_4, product_name_4, product_category_4, product_ndc_4,
            product_type_5, product_name_5, product_category_5, product_ndc_5
        )
        SELECT
            staging_id,
            record_id,
            change_type,
            NULLIF(program_year, '') as program_year,
            STR_TO_DATE(NULLIF(date_of_payment, ''), '%m/%d/%Y') as payment_date,
            STR_TO_DATE(NULLIF(payment_publication_date, ''), '%m/%d/%Y') as publication_date,
            CAST(NULLIF(total_amount_of_payment_usdollars, '') AS DECIMAL(15,2)) as amount_usd,
            CAST(NULLIF(number_of_payments_included_in_total_amount, '') AS UNSIGNED) as number_of_payments,
            TRIM(nature_of_payment_or_transfer_of_value) as payment_nature,
            TRIM(form_of_payment_or_transfer_of_value) as payment_form,
            covered_recipient_profile_id,
            covered_recipient_npi,
            covered_recipient_type as recipient_type,
            
            TRIM(covered_recipient_first_name),
            TRIM(covered_recipient_middle_name),
            TRIM(covered_recipient_last_name),
            TRIM(covered_recipient_name_suffix),
            TRIM(teaching_hospital_name),
            NULL as recipient_full_name,
            
            TRIM(BOTH '|' FROM CONCAT_WS('|',
                NULLIF(covered_recipient_specialty_1, ''),
                NULLIF(covered_recipient_specialty_2, ''),
                NULLIF(covered_recipient_specialty_3, ''),
                NULLIF(covered_recipient_specialty_4, ''),
                NULLIF(covered_recipient_specialty_5, ''),
                NULLIF(covered_recipient_specialty_6, '')
            )) as recipient_specialty,

            COALESCE(NULLIF(covered_recipient_license_state_code1, ''), NULLIF(covered_recipient_license_state_code2, '')) as recipient_license_state,
            teaching_hospital_ccn,
            TRIM(recipient_primary_business_street_address_line1) as recipient_address_line1,
            TRIM(recipient_primary_business_street_address_line2) as recipient_address_line2,
            TRIM(recipient_city) as recipient_city,
            TRIM(recipient_state) as recipient_state,
            recipient_zip_code as recipient_zip, 
            recipient_country as recipient_country,
            recipient_province as recipient_province,
            
            submitting_applicable_mfr_or_gpo_name as payer_name,
            applicable_mfr_or_gpo_making_payment_id as payer_id,
            applicable_mfr_or_gpo_making_payment_name as subsidiary_name,
            applicable_mfr_or_gpo_making_payment_id as subsidiary_id,
            applicable_mfr_or_gpo_making_payment_state as subsidiary_state,
            applicable_mfr_or_gpo_making_payment_country as subsidiary_country,
            
            name_of_third_party_entity_receiving_payment as name_of_third_party_entity,
            
            physician_ownership_indicator,
            third_party_payment_recipient_indicator,
            charity_indicator,
            related_product_indicator,
            dispute_status_for_publication as dispute_status,
            contextual_information,
            city_of_travel as travel_city,
            state_of_travel as travel_state,
            country_of_travel as travel_country,
            
            indicate_drug_or_biological_or_device_or_supply_1,
            TRIM(name_of_drug_or_biological_or_device_or_supply_1),
            TRIM(product_category_or_therapeutic_area_1),
            associated_drug_or_biological_ndc_1,
            
            indicate_drug_or_biological_or_device_or_supply_2,
            TRIM(name_of_drug_or_biological_or_device_or_supply_2),
            TRIM(product_category_or_therapeutic_area_2),
            associated_drug_or_biological_ndc_2,
            
            indicate_drug_or_biological_or_device_or_supply_3,
            TRIM(name_of_drug_or_biological_or_device_or_supply_3),
            TRIM(product_category_or_therapeutic_area_3),
            associated_drug_or_biological_ndc_3,
            
            indicate_drug_or_biological_or_device_or_supply_4,
            TRIM(name_of_drug_or_biological_or_device_or_supply_4),
            TRIM(product_category_or_therapeutic_area_4),
            associated_drug_or_biological_ndc_4,
            
            indicate_drug_or_biological_or_device_or_supply_5,
            TRIM(name_of_drug_or_biological_or_device_or_supply_5),
            TRIM(product_category_or_therapeutic_area_5),
            associated_drug_or_biological_ndc_5
            
        FROM stg_general_payments
        WHERE staging_id >= current_id AND staging_id < current_id + batch_size;
        
        SET rows_in_this_batch = ROW_COUNT();
        SET total_rows_migrated = total_rows_migrated + rows_in_this_batch;

        -- Log BATCH progress
        INSERT INTO migration_log (process_name, log_type, batch_end_id, rows_processed) 
        VALUES ('MigrateStaging', 'BATCH', current_id + batch_size - 1, rows_in_this_batch);
        
        COMMIT;
        
        SET current_id = current_id + batch_size;
    END WHILE;
    -- END OF LOOP

    -- Log FINAL SUMMARY
    INSERT INTO migration_log (process_name, log_type, batch_end_id, rows_processed, notes) 
    VALUES ('MigrateStaging', 'SUMMARY', max_id, total_rows_migrated, 'Migration complete');
    
    SELECT CONCAT('Migration Complete. Total Rows: ', total_rows_migrated) as FinalStatus;
END $$

DELIMITER ;

-- Execute Workflow
CALL MigrateStaging();